FROM quay.io/keycloak/keycloak:18.0.2 as builder
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=false
ENV KC_FEATURES=token-exchange,recovery-codes
ENV KC_DB=postgres
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:18.0.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

ARG CAPROVER_APP=${CAPROVER_APP}
ARG CAPROVER_NAME=${CAPROVER_NAME}
ARG CAPROVER_ROOT=${CAPROVER_ROOT}

ARG CODA_AUTH_SERVICE_DB_HOST=${CODA_AUTH_SERVICE_DB_HOST}
ARG CODA_AUTH_SERVICE_DB_NAME=${CODA_AUTH_SERVICE_DB_NAME}
ARG CODA_AUTH_SERVICE_DB_USERNAME=${CODA_AUTH_SERVICE_DB_USERNAME}
ARG CODA_AUTH_SERVICE_DB_PASSWORD=${CODA_AUTH_SERVICE_DB_PASSWORD}

ARG CODA_AUTH_SERVICE_ADMIN_USERNAME=${CODA_AUTH_SERVICE_ADMIN_USERNAME}
ARG CODA_AUTH_SERVICE_ADMIN_PASSWORD=${CODA_AUTH_SERVICE_ADMIN_PASSWORD}

ENV CAPROVER_APP=${CAPROVER_APP}
ENV CAPROVER_NAME=${CAPROVER_NAME}
ENV CAPROVER_ROOT=${CAPROVER_ROOT}

ENV KC_DB_URL=jdbc:postgresql://${CODA_AUTH_SERVICE_DB_HOST}/${CODA_AUTH_SERVICE_DB_NAME}
ENV KC_DB_USERNAME=${CODA_AUTH_SERVICE_DB_USERNAME}
ENV KC_DB_PASSWORD=${CODA_AUTH_SERVICE_DB_PASSWORD}

ENV KEYCLOAK_ADMIN=${CODA_AUTH_SERVICE_ADMIN_USERNAME}
ENV KEYCLOAK_ADMIN_PASSWORD=${CODA_AUTH_SERVICE_ADMIN_PASSWORD}

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--hostname=${CAPROVER_APP}.${CAPROVER_NAME}.${CAPROVER_ROOT}", "--proxy=edge", "--http-port ${CODA_AUTH_SERVICE_PORT}"]